# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Criterion 1"
  url = "criterion1/"
  weight = 50
  
[[main]]
  name = "Criterion 2"
  url = "criterion2/"
  weight = 51 

[[main]]
  name = "Criterion 3"
  url = "criterion3/"
  weight = 52 

[[main]]
  name = "Criterion 4"
  url = "criterion4/"
  weight = 53 

[[main]]
  name = "Criterion 5"
  url = "criterion5/"
  weight = 54

[[main]]
  name = "Testimonials & CV"
  url = "testimonials/"
  weight = 54

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
